---
- name: Disable USB Devices on Windows
  hosts: all
  vars:
    mypath: 'HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR'
    myname: 'Start'
    mydata: '4'
    mytype: 'dword'
  tasks:
    - name: Set registry key to disable USBSTOR
      ansible.windows.win_regedit:
        path: "{{ mypath }}"
        name: "{{ myname }}"
        data: "{{ mydata }}"
        type: "{{ mytype }}"
