---
- name: Disable USB Devices on Windows
  hosts: all
  gather_facts: false
  tasks:
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Services\USBSTOR
    name: Start
    data: 4
    type: dword
