---
- name: Export Facts to CSV
  hosts: all
  gather_facts: true

  tasks:
    - name: Collect facts using setup module
      setup:

    - name: Create CSV file
      ansible.builtin.template:
        src: facts_template.j2
        dest: /tmp/facts.csv
      delegate_to: localhost
