# Ansible playbook to generate a CSV containing OS & CPU counts for 
# Windows 11 hosts

- hosts: all
  gather_facts: yes
  tasks:

  # This is how filtering can be done
  # In this example, we'll end the play for hosts that do NOT have '2012'
  # in the ansible_os_name field.
  - meta: end_host
    when: ("Windows 11" not in ansible_os_name)

  # Only matching hosts are left now

  # Use the template module to create a CSV file
  - template:
      src: /home/itops/template_ansible/os_cpu_count.csv.j2
      dest: /home/itops/template_ansible/win11_os_report.csv
      remote_src: yes
    vars:
      _hosts: "{{ ansible_play_hosts|list }}"
    delegate_to: localhost
