---
- hosts: all
  gather_facts: true
  tasks:
  - debug:
      var: ansible_hostname
  - debug:
      var: ansible_domain
  - debug:
      var: ansible_fqdn
  - debug:
      var: ansible_distribution
  - debug:
      var: ansible_memtotal_mb
  - template:
      src: template_facts.j2
      dest: /home/itops/win11-facts.csv
    vars:
      _hosts: "{{ ansible_play_hosts|list }}"
    delegate_to: localhost
