---
- hosts: all
  gather_facts: no
  tasks:
  - name: Download s2Store
    win_get_url:
      url: ftp://172.16.195.13/Applikasi%20Retail/S2_STORE_NEW.msi
      dest: C:\temp\S2_STORE_NEW.msi

  - name: Ensure S2 Store is installed with win package
    win_package:
      path: C:\temp\S2_STORE_NEW.msi
      state: present
