- hosts: all
  gather_facts: no
  tasks:
  - name: Install all Windows Updates without a scheduled task
    win_updates:
      category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      - FeaturePacks
      - ServicePacks
      - DefinitionUpdates
      log_path: C:\Temp\ansible-windows-update.txt
      state: installed
      reboot: yes
